syntax = "proto3";
package waproto;

/// WhatsApp Version: 2.3000.1046899131

enum ACK {
	CLOCK = 0;
	SENDER_BACKFILL_SENT = -7;
	INACTIVE_RECEIVED = -6;
	CONTENT_UNUPLOADABLE = -5;
	CONTENT_TOO_BIG = -4;
	CONTENT_GONE = -3;
	EXPIRED = -2;
	FAILED = -1;
	SENT = 1;
	RECEIVED = 2;
	READ = 3;
	PLAYED = 4;
}

enum FAILURE_REASON {
	FAILURE_REASON_UNKNOWN = 0;
	REASON_GENERIC_FAILURE = 400;
	REASON_NOT_AUTHORIZED = 401;
	REASON_TEMP_BANNED = 402;
	REASON_LOCKED = 403;
	REASON_CLIENT_TOO_OLD = 405;
	REASON_BANNED = 406;
	REASON_BAD_USER_AGENT = 409;
	REASON_INTERNAL_SERVER_ERROR = 500;
	REASON_EXPERIMENTAL = 501;
	REASON_SERVICE_UNAVAILABLE = 503;
}

enum FALCO_MIGRATION_BATCHES {
	FALCO_MIGRATION_BATCHES_UNKNOWN = 0;
	 = 15;
	 = 16;
	 = 9;
	 = 5;
	 = 6;
	 = 15;
	 = 15;
	 = 16;
	 = 15;
	 = 16;
	 = 15;
	 = 8;
	 = 7;
	 = 7;
	 = 3;
	 = 4;
	 = 6;
	 = 7;
	 = 11;
	 = 12;
	 = 15;
	 = 13;
	 = 9;
	 = 16;
	 = 16;
	 = 11;
	 = 11;
	 = 16;
	 = 15;
	 = 16;
	 = 15;
	 = 14;
	 = 16;
	 = 9;
	 = 9;
	 = 16;
	 = 4;
	 = 12;
	 = 9;
	 = 12;
	 = 8;
	 = 13;
	 = 4;
	 = 12;
	 = 15;
	 = 12;
	 = 15;
	 = 16;
	 = 8;
	 = 13;
	 = 16;
	 = 9;
	 = 11;
	 = 4;
	 = 16;
	 = 15;
	 = 16;
	 = 15;
	 = 16;
	 = 15;
	 = 12;
	 = 7;
	 = 4;
	 = 16;
	 = 13;
	 = 13;
	 = 5;
	 = 13;
	 = 15;
	 = 13;
	 = 6;
	 = 9;
	 = 11;
	 = 15;
	 = 8;
	 = 10;
	 = 9;
	 = 11;
	 = 14;
	 = 4;
	 = 9;
	 = 4;
	 = 15;
	 = 9;
	 = 15;
	 = 11;
	 = 5;
	 = 9;
	 = 15;
	 = 15;
	 = 16;
	 = 4;
	 = 9;
	 = 12;
	 = 7;
	 = 16;
	 = 16;
	 = 8;
	 = 9;
	 = 13;
	 = 4;
	 = 4;
	 = 15;
	 = 3;
	 = 15;
	 = 3;
	 = 10;
	 = 16;
	 = 4;
	 = 3;
	 = 7;
	 = 6;
	 = 3;
	 = 6;
	 = 9;
	 = 16;
	 = 11;
	 = 4;
	 = 15;
	 = 12;
	 = 9;
	 = 4;
	 = 15;
	 = 16;
	 = 16;
	 = 16;
	 = 8;
	 = 11;
	 = 11;
	 = 15;
	 = 4;
	 = 6;
	 = 5;
	 = 7;
	 = 7;
	 = 10;
	 = 13;
	 = 11;
	 = 3;
	 = 3;
	 = 6;
	 = 15;
	 = 6;
	 = 8;
	 = 3;
	 = 9;
	 = 13;
	 = 14;
	 = 8;
	 = 7;
	 = 14;
	 = 6;
	 = 6;
	 = 6;
	 = 5;
	 = 15;
	 = 5;
	 = 6;
	 = 7;
	 = 16;
	 = 9;
	 = 8;
	 = 3;
	 = 4;
	 = 16;
	 = 14;
	 = 11;
	 = 7;
	 = 3;
	 = 3;
	 = 12;
	 = 13;
	 = 11;
	 = 7;
	 = 6;
	 = 16;
	 = 16;
	 = 15;
	 = 3;
	 = 16;
	 = 15;
	 = 16;
	 = 13;
	 = 15;
	 = 16;
	 = 16;
	 = 7;
	 = 13;
	 = 8;
	 = 15;
	 = 13;
	 = 9;
	 = 7;
	 = 7;
	 = 10;
	 = 15;
	 = 6;
	 = 15;
	 = 7;
	 = 11;
	 = 8;
	 = 6;
	 = 16;
	 = 6;
	 = 8;
	 = 3;
	 = 16;
	 = 11;
	 = 13;
	 = 8;
	 = 12;
	 = 12;
	 = 4;
	 = 15;
	 = 3;
	 = 11;
	 = 11;
	 = 6;
	 = 11;
	 = 6;
	 = 16;
	 = 13;
	 = 8;
	 = 13;
	 = 16;
	 = 15;
	 = 15;
	 = 14;
	 = 4;
	 = 12;
	 = 6;
	 = 7;
	 = 5;
	 = 5;
	 = 4;
	 = 16;
	 = 7;
	 = 16;
	 = 16;
	 = 15;
	 = 11;
	 = 15;
	 = 9;
	 = 15;
	 = 8;
	 = 12;
	 = 3;
	 = 6;
	 = 15;
	 = 7;
	 = 11;
	 = 13;
	 = 10;
	 = 13;
	 = 11;
	 = 7;
	 = 14;
	 = 16;
	 = 4;
	 = 16;
	 = 3;
	 = 9;
	 = 16;
	 = 7;
	 = 8;
	 = 15;
	 = 16;
	 = 13;
	 = 15;
	 = 12;
	 = 12;
	 = 15;
	 = 16;
	 = 15;
	 = 11;
	 = 12;
	 = 7;
	 = 4;
	 = 3;
	 = 13;
	 = 5;
	 = 15;
	 = 12;
	 = 9;
	 = 11;
	 = 5;
	 = 11;
	 = 12;
	 = 9;
	 = 10;
	 = 13;
	 = 9;
	 = 8;
	 = 4;
	 = 15;
	 = 10;
	 = 16;
	 = 6;
	 = 16;
	 = 8;
	 = 16;
	 = 15;
	 = 16;
	 = 9;
	 = 11;
	 = 13;
	 = 5;
	 = 13;
	 = 15;
	 = 4;
	 = 15;
	 = 16;
	 = 15;
	 = 11;
	 = 15;
	 = 15;
	 = 13;
	 = 15;
	 = 16;
	 = 16;
	 = 4;
	 = 16;
	 = 16;
	 = 16;
	 = 16;
	 = 12;
	 = 11;
	 = 16;
	 = 8;
	 = 3;
	 = 12;
	 = 16;
	 = 8;
	 = 12;
	 = 6;
	 = 3;
	 = 16;
	 = 16;
	 = 12;
	 = 16;
	 = 6;
	 = 16;
	 = 5;
	 = 9;
	 = 9;
	 = 15;
	 = 10;
	 = 15;
	 = 9;
	 = 13;
	 = 3;
	 = 15;
	 = 8;
	 = 16;
	 = 15;
	 = 16;
	 = 9;
	 = 9;
	 = 4;
	 = 3;
	 = 7;
	 = 4;
	 = 15;
	 = 15;
	 = 6;
	 = 15;
	 = 16;
	 = 16;
	 = 7;
	 = 7;
	 = 10;
	 = 10;
	 = 15;
	 = 15;
	 = 10;
	 = 13;
	 = 15;
	 = 16;
	 = 3;
	 = 15;
	 = 7;
	 = 5;
	 = 15;
	 = 15;
	 = 16;
	 = 9;
	 = 16;
	 = 16;
	 = 4;
	 = 15;
	 = 15;
	 = 5;
	 = 16;
	 = 4;
	 = 16;
	 = 15;
	 = 15;
	 = 16;
	 = 3;
	 = 15;
	 = 15;
	 = 15;
	 = 14;
	 = 16;
	 = 5;
	 = 6;
	 = 2;
	 = 15;
	 = 16;
	 = 16;
	 = 15;
	 = 16;
	 = 15;
	 = 11;
	 = 15;
	 = 11;
	 = 13;
	 = 15;
	 = 15;
	 = 16;
	 = 16;
	 = 15;
	 = 7;
	 = 8;
	 = 3;
	 = 4;
	 = 9;
	 = 15;
	 = 15;
	 = 5;
	 = 3;
	 = 7;
	 = 15;
	 = 15;
	 = 16;
	 = 7;
	 = 15;
	 = 15;
	 = 4;
	 = 9;
	 = 11;
	 = 16;
	 = 11;
	 = 15;
	 = 16;
	 = 16;
	 = 16;
	 = 15;
	 = 16;
	 = 15;
	 = 8;
	 = 7;
	 = 15;
}

enum TAB_ORDER {
	TAB_ORDER_UNKNOWN = 0;
	STATUS_HEADER_SECTION = 1;
	STATUS_MIDDLE_SECTION = 2;
	STATUS_QUICK_REPLIES_SECTION = 3;
	STATUS_BOTTOM_SECTION = 4;
	CHATLIST_HEADER = 2;
	NEWSLETTER_TAB_HEADER = 2;
	TAB_HEADER = 2;
	LABELS_TAB_HEADER = 2;
	NEW_CHAT_ENTRY_POINT = 2;
	CHAT_STARRED_DRAWER = 3;
	CHAT_LIST_SEARCH = 3;
	CHAT_LIST_FILTER = 3;
	BUTTER_BAR = 4;
	NEWSLETTER_TAB_FILTERS = 4;
	RESPONSES_TAB_FILTERS = 4;
	ARCHIVED_ENTRY_POINT = 4;
	CHAT_LIST = 4;
	NEWSLETTER_TAB_LIST = 4;
	NEWSLETTER_TAB_RECOMMENDED_LIST = 4;
	NEWSLETTER_TAB_RECOMMENDED_BUTTON = 4;
	NEWSLETTER_TAB_CREATE_CHANNEL_BUTTON = 4;
	E2E_MESSAGE_BTN = 4;
	CHAT_CONTACT_LIST = 4;
	CHAT_IMAGE_GALLERY = 4;
	CHAT_SEARCH_MSG_LIST = 4;
	PANEL_SEARCH_INPUT = 5;
	CHAT_HEADER_BUTTON = 6;
	MESSAGE_LIST_SCROLL_BUTTON = 7;
	EMPTY_STATE = 8;
	MESSAGE_LIST = 8;
	CONTEXT_CARD = 9;
	PTT_OOC_BUTTON = 9;
	CHAT_SELECT_BAR = 10;
	POPUP_PANEL = 9;
	COMPOSE_BOX_MENU_BUTTON = 10;
	COMPOSE_BOX_INPUT = 10;
	COMPOSE_BOX_ATTACH_BUTTON = 10;
	COMPOSE_BOX_EXPRESSION_PICKER = 10;
	COMPOSE_BOX_MODE_PILL = 10;
	GROUP_MSG_BAR_LEARN_MORE = 10;
	PTT_BUTTON = 11;
	SEND_BUTTON = 11;
	PIP_PLAYER = 12;
	DRAWER_HEADER = 1;
	DRAWER_CONTENT = 3;
	DRAWER_FOOTER = 5;
}

enum TYPES {
	INT = 0;
	BOOL = 1;
	STRING = 2;
	FLOAT = 3;
}

enum defaultProps {
	forceResetErrorCount = 0;
}

enum exports {
	NOT_A_PERSON = 0;
	FEMALE_PLURAL = 8;
	FEMALE_SINGULAR = 1;
	FEMALE_SINGULAR_GUESS = 3;
	MALE_PLURAL = 9;
	MALE_SINGULAR = 2;
	MALE_SINGULAR_GUESS = 4;
	MIXED_UNKNOWN = 5;
	NEUTER_PLURAL = 10;
	NEUTER_SINGULAR = 6;
	UNKNOWN_PLURAL = 11;
	UNKNOWN_SINGULAR = 7;
}

enum exports {
	EXPORTS_UNKNOWN = 0;
	BITMASK_GENDER = 3;
	BITMASK_NUMBER = 28;
	GENDER_FEMALE = 2;
	GENDER_MALE = 1;
	GENDER_UNKNOWN = 3;
	NUMBER_FEW = 20;
	NUMBER_MANY = 12;
	NUMBER_ONE = 4;
	NUMBER_OTHER = 24;
	NUMBER_TWO = 8;
	NUMBER_ZERO = 16;
}

