package catalog
import "strings"

// PackageMeta defines metadata for a modular wa-core protobuf package.
type PackageMeta struct {
	Dir       string
	File      string
	Package   string
	GoPackage string
	Messages  []string
	Enums     []string
	Imports   []string
}

// Packages holds the registry of all standard wa-core proto packages.
var Packages = map[string]*PackageMeta{
	"instamadilloAddMessage": {
		Dir: "instamadilloAddMessage",
		File: "InstamadilloAddMessage.proto",
		Package: "InstamadilloAddMessage",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloAddMessage",
		Messages: []string{
			"AddMessageContent",
			"AddMessageMetadata",
			"AddMessagePayload",
			"EphemeralityParams",
			"ForwardingParams",
			"Like",
			"OpenMessageMicroSecondTimestamp",
			"Placeholder",
			"PrivateReplyInfo",
			"ReceiverFetchXma",
			"RepliedToMessage",
		},
		Enums: []string{
			"Type",
		},
		Imports: []string{
			"instamadilloCoreTypeActionLog/InstamadilloCoreTypeActionLog.proto",
			"instamadilloCoreTypeAdminMessage/InstamadilloCoreTypeAdminMessage.proto",
			"instamadilloCoreTypeCollection/InstamadilloCoreTypeCollection.proto",
			"instamadilloCoreTypeLink/InstamadilloCoreTypeLink.proto",
			"instamadilloCoreTypeMedia/InstamadilloCoreTypeMedia.proto",
			"instamadilloCoreTypeText/InstamadilloCoreTypeText.proto",
			"instamadilloXmaContentRef/InstamadilloXmaContentRef.proto",
		},
	},
	"instamadilloCoreTypeActionLog": {
		Dir: "instamadilloCoreTypeActionLog",
		File: "InstamadilloCoreTypeActionLog.proto",
		Package: "InstamadilloCoreTypeActionLog",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeActionLog",
		Messages: []string{
			"ActionLog",
			"ActionLogReaction",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"instamadilloCoreTypeAdminMessage": {
		Dir: "instamadilloCoreTypeAdminMessage",
		File: "InstamadilloCoreTypeAdminMessage.proto",
		Package: "InstamadilloCoreTypeAdminMessage",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeAdminMessage",
		Messages: []string{
			"AdminMessage",
			"DeviceAdminMessage",
		},
		Enums: []string{
			"Type",
		},
		Imports: []string{
		},
	},
	"instamadilloCoreTypeCollection": {
		Dir: "instamadilloCoreTypeCollection",
		File: "InstamadilloCoreTypeCollection.proto",
		Package: "InstamadilloCoreTypeCollection",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeCollection",
		Messages: []string{
			"Collection",
		},
		Enums: []string{
		},
		Imports: []string{
			"instamadilloCoreTypeMedia/InstamadilloCoreTypeMedia.proto",
		},
	},
	"instamadilloCoreTypeLink": {
		Dir: "instamadilloCoreTypeLink",
		File: "InstamadilloCoreTypeLink.proto",
		Package: "InstamadilloCoreTypeLink",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeLink",
		Messages: []string{
			"ImageUrl",
			"Link",
			"LinkContext",
		},
		Enums: []string{
		},
		Imports: []string{
			"instamadilloCoreTypeMedia/InstamadilloCoreTypeMedia.proto",
		},
	},
	"instamadilloCoreTypeMedia": {
		Dir: "instamadilloCoreTypeMedia",
		File: "InstamadilloCoreTypeMedia.proto",
		Package: "InstamadilloCoreTypeMedia",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeMedia",
		Messages: []string{
			"AvatarSticker",
			"CommonMediaTransport",
			"Gif",
			"Media",
			"Raven",
			"RavenContent",
			"StaticPhoto",
			"Thumbnail",
			"Video",
			"VideoExtraMetadata",
			"Voice",
		},
		Enums: []string{
			"InterventionType",
			"PjpegScanConfiguration",
			"ViewMode",
		},
		Imports: []string{
		},
	},
	"instamadilloCoreTypeText": {
		Dir: "instamadilloCoreTypeText",
		File: "InstamadilloCoreTypeText.proto",
		Package: "InstamadilloCoreTypeText",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloCoreTypeText",
		Messages: []string{
			"AnimatedEmojiCharacterRange",
			"CommandRangeData",
			"FormattedText",
			"PowerUpsData",
			"Text",
		},
		Enums: []string{
			"FormatStyle",
		},
		Imports: []string{
			"instamadilloCoreTypeMedia/InstamadilloCoreTypeMedia.proto",
		},
	},
	"instamadilloDeleteMessage": {
		Dir: "instamadilloDeleteMessage",
		File: "InstamadilloDeleteMessage.proto",
		Package: "InstamadilloDeleteMessage",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloDeleteMessage",
		Messages: []string{
			"DeleteMessagePayload",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"instamadilloSupplementMessage": {
		Dir: "instamadilloSupplementMessage",
		File: "InstamadilloSupplementMessage.proto",
		Package: "InstamadilloSupplementMessage",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloSupplementMessage",
		Messages: []string{
			"ContentView",
			"EditText",
			"MediaInterventions",
			"MediaReaction",
			"OriginalTransportPayload",
			"Reaction",
			"SupplementMessageContent",
			"SupplementMessagePayload",
		},
		Enums: []string{
		},
		Imports: []string{
			"instamadilloCoreTypeMedia/InstamadilloCoreTypeMedia.proto",
		},
	},
	"instamadilloTransportPayload": {
		Dir: "instamadilloTransportPayload",
		File: "InstamadilloTransportPayload.proto",
		Package: "InstamadilloTransportPayload",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloTransportPayload",
		Messages: []string{
			"Franking",
			"TransportPayload",
		},
		Enums: []string{
			"PayloadCreator",
		},
		Imports: []string{
			"instamadilloAddMessage/InstamadilloAddMessage.proto",
			"instamadilloDeleteMessage/InstamadilloDeleteMessage.proto",
			"instamadilloSupplementMessage/InstamadilloSupplementMessage.proto",
		},
	},
	"instamadilloXmaContentRef": {
		Dir: "instamadilloXmaContentRef",
		File: "InstamadilloXmaContentRef.proto",
		Package: "InstamadilloXmaContentRef",
		GoPackage: "go.mau.fi/whatsmeow/proto/instamadilloXmaContentRef",
		Messages: []string{
			"ReceiverFetchXmaClipFetchParams",
			"ReceiverFetchXmaCommentFetchParams",
			"ReceiverFetchXmaFeedFetchParams",
			"ReceiverFetchXmaFetchParams",
			"ReceiverFetchXmaLiveFetchParams",
			"ReceiverFetchXmaLocationShareFetchParams",
			"ReceiverFetchXmaMediaNoteFetchParams",
			"ReceiverFetchXmaNoteFetchParams",
			"ReceiverFetchXmaProfileFetchParams",
			"ReceiverFetchXmaReelsAudioFetchParams",
			"ReceiverFetchXmaSocialContextFetchParams",
			"ReceiverFetchXmaStoryFetchParams",
			"XmaContentRef",
		},
		Enums: []string{
			"MediaNoteFetchParamsMessageType",
			"ReceiverFetchContentType",
			"XmaActionType",
		},
		Imports: []string{
		},
	},
	"waAICommon": {
		Dir: "waAICommon",
		File: "WAWebProtobufsAICommon.proto",
		Package: "WAWebProtobufsAICommon",
		GoPackage: "go.mau.fi/whatsmeow/proto/waAICommon",
		Messages: []string{
			"AIHomeOption",
			"AIHomeState",
			"AIMediaCollectionMessage",
			"AIMediaCollectionMetadata",
			"AIMetadataOperation",
			"AIProvenance",
			"AIRegenerateMetadata",
			"AIRichResponseUnifiedResponse",
			"AISubscriptionUpsellMetadata",
			"AIThreadClientInfo",
			"AIThreadInfo",
			"AIThreadServerInfo",
			"BotAgeCollectionMetadata",
			"BotAgentDeepLinkMetadata",
			"BotAgentMetadata",
			"BotCapabilityMetadata",
			"BotCommandMetadata",
			"BotDocumentMessageMetadata",
			"BotFeatureQuotaMetadata",
			"BotFeedbackMessage",
			"BotGroupMetadata",
			"BotGroupParticipantMetadata",
			"BotHistoryShareMetadata",
			"BotImagineMetadata",
			"BotInfrastructureDiagnostics",
			"BotLinkedAccount",
			"BotLinkedAccountsMetadata",
			"BotMediaMetadata",
			"BotMemoryFact",
			"BotMemoryMetadata",
			"BotMemuMetadata",
			"BotMessageOrigin",
			"BotMessageOriginMetadata",
			"BotMessageSharingInfo",
			"BotMetadata",
			"BotMetricsMetadata",
			"BotModeSelectionMetadata",
			"BotModelMetadata",
			"BotPlanningSearchSourceMetadata",
			"BotPlanningSearchSourcesMetadata",
			"BotPlanningStepMetadata",
			"BotPlanningStepSectionMetadata",
			"BotPluginMetadata",
			"BotProgressIndicatorMetadata",
			"BotPromotionMessageMetadata",
			"BotPromptSuggestion",
			"BotPromptSuggestions",
			"BotPttPromptMetadata",
			"BotQuotaMetadata",
			"BotReminderMetadata",
			"BotRenderingConfigMetadata",
			"BotRenderingMetadata",
			"BotResolvedToolCallMetadata",
			"BotSessionMetadata",
			"BotSignatureVerificationMetadata",
			"BotSignatureVerificationUseCaseProof",
			"BotSourceItem",
			"BotSourcesMetadata",
			"BotSuggestedPromptMetadata",
			"BotUnifiedResponseMutation",
			"CertificateSKI",
			"ForwardedAIBotMessageInfo",
			"HatchMetadataSync",
			"InThreadSurveyMetadata",
			"InThreadSurveyOption",
			"InThreadSurveyPrivacyStatementPart",
			"InThreadSurveyQuestion",
			"Keyword",
			"MediaDetailsMetadata",
			"Metadata",
			"SessionTransparencyMetadata",
			"SideBySideMetadata",
			"SideBySideSurveyAbandonEventData",
			"SideBySideSurveyAnalyticsData",
			"SideBySideSurveyCTAClickEventData",
			"SideBySideSurveyCTAImpressionEventData",
			"SideBySideSurveyCardImpressionEventData",
			"SideBySideSurveyMetadata",
			"SideBySideSurveyResponseEventData",
			"SidebySideSurveyMetaAiAnalyticsData",
		},
		Enums: []string{
			"AIHomeActionType",
			"AISubscriptionRequestType",
			"AIThreadType",
			"AgeCollectionType",
			"BotBackend",
			"BotCapabilityType",
			"BotFeatureType",
			"BotFeedbackKind",
			"BotFeedbackKindMultipleNegative",
			"BotFeedbackKindMultiplePositive",
			"BotLinkedAccountType",
			"BotMessageOriginType",
			"BotMetricsEntryPoint",
			"BotMetricsThreadEntryPoint",
			"BotPlanningSearchSourceProvider",
			"BotPromotionType",
			"BotSearchSourceProvider",
			"BotSessionSource",
			"BotSignatureUseCase",
			"BotUserSelectionMode",
			"DocumentPluginType",
			"ImagineType",
			"ModelType",
			"OrientationType",
			"PlanningStepStatus",
			"PluginType",
			"PremiumModelStatus",
			"ReminderAction",
			"ReminderFrequency",
			"ReportKind",
			"SearchProvider",
			"SessionTransparencyType",
			"SourceProvider",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waAICommonDeprecated": {
		Dir: "waAICommonDeprecated",
		File: "WAAICommonDeprecated.proto",
		Package: "WAAICommonDeprecated",
		GoPackage: "go.mau.fi/whatsmeow/proto/waAICommonDeprecated",
		Messages: []string{
			"AIRichResponseCodeBlock",
			"AIRichResponseCodeMetadata",
			"AIRichResponseContentItemMetadata",
			"AIRichResponseContentItemsMetadata",
			"AIRichResponseDynamicMetadata",
			"AIRichResponseGridImageMetadata",
			"AIRichResponseImageURL",
			"AIRichResponseInlineImageMetadata",
			"AIRichResponseLatexExpression",
			"AIRichResponseLatexMetadata",
			"AIRichResponseMapAnnotation",
			"AIRichResponseMapMetadata",
			"AIRichResponseReelItem",
			"AIRichResponseSubMessage",
			"AIRichResponseTableMetadata",
			"AIRichResponseTableRow",
		},
		Enums: []string{
			"AIRichResponseCodeHighlightType",
			"AIRichResponseDynamicMetadataType",
			"AIRichResponseImageAlignment",
			"AIRichResponseMessageType",
			"AIRichResponseSubMessageType",
			"ContentType",
		},
		Imports: []string{
		},
	},
	"waAdv": {
		Dir: "waAdv",
		File: "WAAdv.proto",
		Package: "WAAdv",
		GoPackage: "go.mau.fi/whatsmeow/proto/waAdv",
		Messages: []string{
			"ADVDeviceIdentity",
			"ADVKeyIndexList",
			"ADVSignedDeviceIdentity",
			"ADVSignedDeviceIdentityHMAC",
			"ADVSignedKeyIndexList",
		},
		Enums: []string{
			"ADVEncryptionType",
		},
		Imports: []string{
		},
	},
	"waAea": {
		Dir: "waAea",
		File: "WAWebProtobufsAea.proto",
		Package: "WAWebProtobufsAea",
		GoPackage: "go.mau.fi/whatsmeow/proto/waAea",
		Messages: []string{
			"NonE2EEAttestation",
		},
		Enums: []string{
			"AccountType",
		},
		Imports: []string{
		},
	},
	"waArmadilloApplication": {
		Dir: "waArmadilloApplication",
		File: "WAArmadilloApplication.proto",
		Package: "WAArmadilloApplication",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloApplication",
		Messages: []string{
			"AIBotResponseMessage",
			"ActionChatArchive",
			"ActionChatDelete",
			"ActionChatRead",
			"ActionMessageDelete",
			"ApplicationData",
			"Armadillo",
			"BumpExistingMessage",
			"CommonSticker",
			"Content",
			"EncryptedBackupsSecrets",
			"Epoch",
			"ExtendedContentMessageWithSear",
			"ImageGalleryMessage",
			"MessageHistoryDocumentMessage",
			"Metadata",
			"MetadataSyncAction",
			"MetadataSyncNotification",
			"NetworkVerificationMessage",
			"NoteReplyMessage",
			"Payload",
			"PaymentsTransactionMessage",
			"RavenActionNotifMessage",
			"RavenMessage",
			"ScreenshotAction",
			"Signal",
			"SubProtocolPayload",
			"SyncActionMessage",
			"SyncActionMessageRange",
			"SyncAttachmentInterventionAction",
			"SyncChatAction",
			"SyncMessageAction",
			"SyncSpectraAction",
		},
		Enums: []string{
			"ActionType",
			"EphemeralType",
			"EpochStatus",
			"InterventionType",
			"PaymentStatus",
			"ScreenshotType",
			"SpectraActionType",
			"StickerType",
		},
		Imports: []string{
			"waArmadilloXMA/WAArmadilloXMA.proto",
			"waCommon/WACommon.proto",
		},
	},
	"waArmadilloBackupCommon": {
		Dir: "waArmadilloBackupCommon",
		File: "WAArmadilloBackupCommon.proto",
		Package: "WAArmadilloBackupCommon",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloBackupCommon",
		Messages: []string{
			"FrankingMetadata",
			"Metadata",
			"Subprotocol",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waArmadilloBackupMessage": {
		Dir: "waArmadilloBackupMessage",
		File: "WAArmadilloBackupMessage.proto",
		Package: "WAArmadilloBackupMessage",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloBackupMessage",
		Messages: []string{
			"BackupMessage",
		},
		Enums: []string{
		},
		Imports: []string{
			"waArmadilloBackupCommon/WAArmadilloBackupCommon.proto",
		},
	},
	"waArmadilloICDC": {
		Dir: "waArmadilloICDC",
		File: "WAArmadilloICDC.proto",
		Package: "WAArmadilloICDC",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloICDC",
		Messages: []string{
			"ICDCIdentityList",
			"SignedICDCIdentityList",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waArmadilloMiTransportAdminMessage": {
		Dir: "waArmadilloMiTransportAdminMessage",
		File: "WAArmadilloMiTransportAdminMessage.proto",
		Package: "WAArmadilloMiTransportAdminMessage",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloMiTransportAdminMessage",
		Messages: []string{
			"ChatThemeChanged",
			"DisappearingSettingChanged",
			"GroupAdminChanged",
			"GroupImageChanged",
			"GroupMembershipAddModeChanged",
			"GroupNameChanged",
			"GroupParticipantChanged",
			"IconChanged",
			"LimitSharingChanged",
			"LinkCta",
			"MessagePinned",
			"MiTransportAdminMessage",
			"NicknameChanged",
			"QuickReactionChanged",
			"RemovedContentTuple",
			"UkOsaAdminText",
			"XmatAddParticipants",
			"XmatChangeThreadAdmins",
			"XmatChangeThreadName",
			"XmatDisappearingSetting",
			"XmatFriendRequestConfirmedEncrypted",
			"XmatGenAITaskAdd",
			"XmatGroupThreadCreated",
			"XmatInstantGameEncryptedDynamicCustomUpdate",
			"XmatLinkCTA",
			"XmatMagicWords",
			"XmatMessagingLimitSharing",
			"XmatMessengerMessageReminderSet",
			"XmatMessengerMessageReminderTriggered",
			"XmatMessengerQRCodeScanned",
			"XmatMessengerSharedAlbum",
			"XmatMessengerSharedAlbumAddition",
			"XmatMessengerSharedAlbumContentRemoval",
			"XmatMessengerSharedAlbumDeletion",
			"XmatMessengerSharedAlbumRename",
			"XmatPinMessageV2",
			"XmatRemoveParticipant",
			"XmatSetParticipantUpdateMode",
			"XmatThemeColor",
			"XmatThreadIcon",
			"XmatThreadNickname",
			"XmatThreadQuickReaction",
			"XmatUnpinMessageV2",
			"XmatUpdatePayments",
		},
		Enums: []string{
			"Action",
			"Action",
			"Action",
			"Action",
			"Mode",
			"SharingType",
		},
		Imports: []string{
		},
	},
	"waArmadilloTransportEvent": {
		Dir: "waArmadilloTransportEvent",
		File: "WAArmadilloTransportEvent.proto",
		Package: "WAArmadilloTransportEvent",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloTransportEvent",
		Messages: []string{
			"DeviceChange",
			"Event",
			"IcdcAlert",
			"Placeholder",
			"TransportEvent",
		},
		Enums: []string{
			"Type",
			"Type",
			"Type",
		},
		Imports: []string{
		},
	},
	"waArmadilloXMA": {
		Dir: "waArmadilloXMA",
		File: "WAArmadilloXMA.proto",
		Package: "WAArmadilloXMA",
		GoPackage: "go.mau.fi/whatsmeow/proto/waArmadilloXMA",
		Messages: []string{
			"CTA",
			"ExtendedContentMessage",
		},
		Enums: []string{
			"CtaButtonType",
			"ExtendedContentType",
			"OverlayIconGlyph",
			"XmaDataclassType",
			"XmaLayoutType",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waBotMetadata": {
		Dir: "waBotMetadata",
		File: "WABotMetadata.proto",
		Package: "WABotMetadata",
		GoPackage: "go.mau.fi/whatsmeow/proto/waBotMetadata",
		Messages: []string{
			"AIThreadClientInfo",
			"AIThreadInfo",
			"AIThreadServerInfo",
			"BotAgeCollectionMetadata",
			"BotAvatarMetadata",
			"BotCapabilityMetadata",
			"BotFeatureQuotaMetadata",
			"BotImagineMetadata",
			"BotLinkedAccount",
			"BotLinkedAccountsMetadata",
			"BotMediaMetadata",
			"BotMemoryFact",
			"BotMemoryMetadata",
			"BotMemuMetadata",
			"BotMessageOrigin",
			"BotMessageOriginMetadata",
			"BotMetadata",
			"BotMetricsMetadata",
			"BotModeSelectionMetadata",
			"BotModelMetadata",
			"BotPlanningSearchSourceMetadata",
			"BotPlanningSearchSourcesMetadata",
			"BotPlanningStepMetadata",
			"BotPlanningStepSectionMetadata",
			"BotPluginMetadata",
			"BotProgressIndicatorMetadata",
			"BotPromotionMessageMetadata",
			"BotPromptSuggestion",
			"BotPromptSuggestions",
			"BotQuotaMetadata",
			"BotReminderMetadata",
			"BotRenderingMetadata",
			"BotSessionMetadata",
			"BotSignatureVerificationMetadata",
			"BotSignatureVerificationUseCaseProof",
			"BotSourceItem",
			"BotSourcesMetadata",
			"BotSuggestedPromptMetadata",
			"BotUnifiedResponseMutation",
			"InThreadSurveyMetadata",
			"InThreadSurveyOption",
			"InThreadSurveyPrivacyStatementPart",
			"InThreadSurveyQuestion",
			"Keyword",
			"MediaDetailsMetadata",
			"SideBySideMetadata",
		},
		Enums: []string{
			"AIThreadType",
			"BotCapabilityType",
			"BotFeatureType",
			"BotLinkedAccountType",
			"BotMessageOriginType",
			"BotMetricsEntryPoint",
			"BotMetricsThreadEntryPoint",
			"BotPlanningSearchSourceProvider",
			"BotPromotionType",
			"BotSearchSourceProvider",
			"BotSessionSource",
			"BotSignatureUseCase",
			"BotUserSelectionMode",
			"ImagineType",
			"ModelType",
			"OrientationType",
			"PlanningStepStatus",
			"PluginType",
			"PremiumModelStatus",
			"ReminderAction",
			"ReminderFrequency",
			"SearchProvider",
			"SourceProvider",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waCert": {
		Dir: "waCert",
		File: "WACert.proto",
		Package: "WACert",
		GoPackage: "go.mau.fi/whatsmeow/proto/waCert",
		Messages: []string{
			"CertChain",
			"Details",
			"Details",
			"NoiseCertificate",
			"NoiseCertificate",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waChatLockSettings": {
		Dir: "waChatLockSettings",
		File: "WAWebProtobufsChatLockSettings.proto",
		Package: "WAWebProtobufsChatLockSettings",
		GoPackage: "go.mau.fi/whatsmeow/proto/waChatLockSettings",
		Messages: []string{
			"ChatLockSettings",
		},
		Enums: []string{
		},
		Imports: []string{
			"waUserPassword/WAWebProtobufsUserPassword.proto",
		},
	},
	"waCommon": {
		Dir: "waCommon",
		File: "WACommon.proto",
		Package: "WACommon",
		GoPackage: "go.mau.fi/whatsmeow/proto/waCommon",
		Messages: []string{
			"Command",
			"LimitSharing",
			"Mention",
			"MessageKey",
			"MessageText",
			"SubProtocol",
		},
		Enums: []string{
			"CommandType",
			"FutureProofBehavior",
			"MentionType",
			"Trigger",
		},
		Imports: []string{
		},
	},
	"waCommonParameterised": {
		Dir: "waCommonParameterised",
		File: "WACommonParameterised.proto",
		Package: "WACommonParameterised",
		GoPackage: "go.mau.fi/whatsmeow/proto/waCommonParameterised",
		Messages: []string{
			"Command",
			"Mention",
			"MessageKey",
			"MessageText",
			"SubProtocol",
		},
		Enums: []string{
			"CommandType",
			"FutureProofBehavior",
			"MentionType",
		},
		Imports: []string{
		},
	},
	"waCompanionReg": {
		Dir: "waCompanionReg",
		File: "WACompanionReg.proto",
		Package: "WACompanionReg",
		GoPackage: "go.mau.fi/whatsmeow/proto/waCompanionReg",
		Messages: []string{
			"AppVersion",
			"ClientPairingProps",
			"CompanionCommitment",
			"CompanionEphemeralIdentity",
			"DeviceProps",
			"EncryptedPairingRequest",
			"HistorySyncConfig",
			"PairingRequest",
			"PrimaryEphemeralIdentity",
			"ProloguePayload",
		},
		Enums: []string{
			"PlatformType",
		},
		Imports: []string{
		},
	},
	"waConsumerApplication": {
		Dir: "waConsumerApplication",
		File: "WAConsumerApplication.proto",
		Package: "WAConsumerApplication",
		GoPackage: "go.mau.fi/whatsmeow/proto/waConsumerApplication",
		Messages: []string{
			"ApplicationData",
			"AudioMessage",
			"ConsumerApplication",
			"ContactMessage",
			"ContactsArrayMessage",
			"Content",
			"DocumentMessage",
			"EditMessage",
			"ExtendedTextMessage",
			"GroupInviteMessage",
			"ImageMessage",
			"InteractiveAnnotation",
			"LiveLocationMessage",
			"Location",
			"LocationMessage",
			"MediaPayload",
			"Metadata",
			"Option",
			"Payload",
			"Point",
			"PollAddOptionMessage",
			"PollCreationMessage",
			"PollEncValue",
			"PollUpdateMessage",
			"PollVoteMessage",
			"ReactionMessage",
			"RevokeMessage",
			"Signal",
			"StatusTextMesage",
			"StickerMessage",
			"SubProtocolPayload",
			"VideoMessage",
			"ViewOnceMessage",
		},
		Enums: []string{
			"FontType",
			"PreviewType",
			"SpecialTextSize",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waConsumerApplicationParameterised": {
		Dir: "waConsumerApplicationParameterised",
		File: "WAConsumerApplicationParameterised.proto",
		Package: "WAConsumerApplicationParameterised",
		GoPackage: "go.mau.fi/whatsmeow/proto/waConsumerApplicationParameterised",
		Messages: []string{
			"ApplicationData",
			"AudioMessage",
			"ConsumerApplication",
			"ContactMessage",
			"ContactsArrayMessage",
			"Content",
			"DocumentMessage",
			"EditMessage",
			"ExtendedTextMessage",
			"GroupInviteMessage",
			"ImageMessage",
			"InteractiveAnnotation",
			"LiveLocationMessage",
			"Location",
			"LocationMessage",
			"MediaPayload",
			"Metadata",
			"Option",
			"Payload",
			"Point",
			"PollAddOptionMessage",
			"PollCreationMessage",
			"PollEncValue",
			"PollUpdateMessage",
			"PollVoteMessage",
			"ReactionMessage",
			"RevokeMessage",
			"Signal",
			"StatusTextMesage",
			"StickerMessage",
			"SubProtocolPayload",
			"VideoMessage",
			"ViewOnceMessage",
		},
		Enums: []string{
			"FontType",
			"PreviewType",
			"SpecialTextSize",
		},
		Imports: []string{
			"waCommonParameterised/WACommonParameterised.proto",
		},
	},
	"waDeviceCapabilities": {
		Dir: "waDeviceCapabilities",
		File: "WAWebProtobufsDeviceCapabilities.proto",
		Package: "WAWebProtobufsDeviceCapabilities",
		GoPackage: "go.mau.fi/whatsmeow/proto/waDeviceCapabilities",
		Messages: []string{
			"AiFbidMigration",
			"AiThread",
			"BizAiSettingsSync",
			"BusinessBroadcast",
			"DeviceCapabilities",
			"LIDMigration",
			"UserHasAvatar",
		},
		Enums: []string{
			"ChatLockSupportLevel",
			"MemberNameTagPrimarySupport",
			"SupportLevel",
		},
		Imports: []string{
		},
	},
	"waE2E": {
		Dir: "waE2E",
		File: "WAWebProtobufsE2E.proto",
		Package: "WAWebProtobufsE2E",
		GoPackage: "go.mau.fi/whatsmeow/proto/waE2E",
		Messages: []string{
			"AIQueryFanout",
			"AIRichResponseMessage",
			"ActionLink",
			"AdReplyInfo",
			"AlbumMessage",
			"AppStateFatalExceptionNotification",
			"AppStateSyncKey",
			"AppStateSyncKeyData",
			"AppStateSyncKeyFingerprint",
			"AppStateSyncKeyId",
			"AppStateSyncKeyRequest",
			"AppStateSyncKeyShare",
			"AudioMessage",
			"BCallMessage",
			"BizBroadcastInsightsContactListRequest",
			"BizBroadcastInsightsContactListResponse",
			"BizBroadcastInsightsContactState",
			"BizBroadcastInsightsRefreshRequest",
			"BloksWidget",
			"Body",
			"Body",
			"BotHistoryShareSyncMetadata",
			"BusinessInteractionPills",
			"BusinessMessageForwardInfo",
			"Button",
			"ButtonText",
			"ButtonsMessage",
			"ButtonsResponseMessage",
			"Call",
			"CallButton",
			"CallLogMessage",
			"CallParticipant",
			"CancelPaymentRequestMessage",
			"CarouselMessage",
			"CatalogSnapshot",
			"Chat",
			"ChatCustomImageWallpaper",
			"ChatDefaultWallpaper",
			"ChatSolidColorWallpaper",
			"ChatStockImageWallpaper",
			"ChatThemeSetting",
			"CloudAPIThreadControlNotification",
			"CloudAPIThreadControlNotificationContent",
			"CollectionMessage",
			"CommentMessage",
			"CompanionCanonicalUserNonceFetchRequest",
			"CompanionCanonicalUserNonceFetchResponse",
			"CompanionMetaNonceFetchResponse",
			"ConditionalRevealMessage",
			"ContactMessage",
			"ContactRefreshResponse",
			"ContactsArrayMessage",
			"ContextInfo",
			"DataSharingContext",
			"DeclinePaymentRequestMessage",
			"DeviceListMetadata",
			"DeviceSentMessage",
			"DisappearingMode",
			"DocumentMessage",
			"EmbeddedContent",
			"EmbeddedMessage",
			"EmbeddedMusic",
			"EncCommentMessage",
			"EncEventResponseMessage",
			"EncReactionMessage",
			"EventInviteMessage",
			"EventMessage",
			"EventResponseMessage",
			"ExtendedTextMessage",
			"ExternalAdReplyInfo",
			"FeatureEligibilities",
			"FlowResponsesCsvBundle",
			"Footer",
			"ForwardedNewsletterMessageInfo",
			"FourRowTemplate",
			"FullHistorySyncOnDemandConfig",
			"FullHistorySyncOnDemandRequest",
			"FullHistorySyncOnDemandRequestMetadata",
			"FullHistorySyncOnDemandRequestResponse",
			"FutureProofMessage",
			"GalaxyFlowAction",
			"GroupInviteMessage",
			"GroupMention",
			"GroupRootKeyShare",
			"GroupRootKeyShareEntry",
			"HSMCurrency",
			"HSMDateTime",
			"HSMDateTimeComponent",
			"HSMDateTimeUnixEpoch",
			"HSMLocalizableParameter",
			"Header",
			"HighlyStructuredMessage",
			"HistoryShareMessageEntry",
			"HistorySyncChunkRetryRequest",
			"HistorySyncChunkRetryResponse",
			"HistorySyncMessageAccessStatus",
			"HistorySyncNotification",
			"HistorySyncOnDemandRequest",
			"HydratedCallButton",
			"HydratedFourRowTemplate",
			"HydratedQuickReplyButton",
			"HydratedTemplateButton",
			"HydratedURLButton",
			"ImageMessage",
			"InitialSecurityNotificationSettingSync",
			"InstagramThreadLink",
			"InteractiveAnnotation",
			"InteractiveMessage",
			"InteractiveResponseMessage",
			"InvoiceMessage",
			"KeepInChatMessage",
			"LIDMigrationMappingSyncMessage",
			"LinkPreviewHighQualityThumbnail",
			"LinkPreviewMetadata",
			"LinkPreviewResponse",
			"ListMessage",
			"ListResponseMessage",
			"LiveLocationMessage",
			"Location",
			"LocationMessage",
			"MMSThumbnailMetadata",
			"MarkAsVerifiedAction",
			"MediaData",
			"MediaDomainInfo",
			"MediaNotifyMessage",
			"MemberLabel",
			"Message",
			"MessageAssociation",
			"MessageContextInfo",
			"MessageHistoryBundle",
			"MessageHistoryMetadata",
			"MessageHistoryNotice",
			"MessageSecretMessage",
			"Money",
			"MusicMessage",
			"NativeFlowButton",
			"NativeFlowInfo",
			"NativeFlowMessage",
			"NativeFlowResponseMessage",
			"NewsletterAdminInviteMessage",
			"NewsletterFollowerInviteMessage",
			"Option",
			"OrderMessage",
			"Parameters",
			"PartiallySelectedContent",
			"PaymentBackground",
			"PaymentExtendedMetadata",
			"PaymentInviteMessage",
			"PaymentLinkButton",
			"PaymentLinkHeader",
			"PaymentLinkMetadata",
			"PaymentLinkPreviewMetadata",
			"PaymentLinkProvider",
			"PaymentReminderMessage",
			"PeerDataOperationRequestMessage",
			"PeerDataOperationRequestResponseMessage",
			"PeerDataOperationResult",
			"Pill",
			"PinInChatMessage",
			"PlaceholderMessage",
			"PlaceholderMessageResendRequest",
			"PlaceholderMessageResendResponse",
			"Point",
			"PollAddOptionMessage",
			"PollCreationMessage",
			"PollEncValue",
			"PollResultSnapshotMessage",
			"PollUpdateMessage",
			"PollUpdateMessageMetadata",
			"PollVote",
			"PollVoteMessage",
			"ProcessedVideo",
			"Product",
			"ProductListHeaderImage",
			"ProductListInfo",
			"ProductMessage",
			"ProductSection",
			"ProductSnapshot",
			"ProtocolMessage",
			"QuestionReplyQuotedMessage",
			"QuestionResponseMessage",
			"QuickReplyButton",
			"ReactionMessage",
			"RequestPaymentMessage",
			"RequestPhoneNumberMessage",
			"RequestStickerReupload",
			"RequestUrlPreview",
			"RequestWelcomeMessageMetadata",
			"RootSecretDistributeMessage",
			"Row",
			"ScheduledCallCreationMessage",
			"ScheduledCallEditMessage",
			"SecretEncryptedMessage",
			"Section",
			"SendPaymentMessage",
			"SenderKeyDistributionMessage",
			"ShopMessage",
			"SignedPayload",
			"SingleSelectReply",
			"SplitPaymentMessage",
			"SplitPaymentParticipant",
			"SplitPaymentUpdateMessage",
			"StatusAudienceMetadata",
			"StatusLinkPreviewMetadata",
			"StatusNotificationMessage",
			"StatusQuestionAnswerMessage",
			"StatusQuotedMessage",
			"StatusStickerInteractionMessage",
			"Sticker",
			"StickerMessage",
			"StickerPackMessage",
			"StickerSyncRMRMessage",
			"SyncDCollectionFatalRecoveryRequest",
			"SyncDSnapshotFatalRecoveryResponse",
			"TapLinkAction",
			"TemplateButton",
			"TemplateButtonReplyMessage",
			"TemplateMessage",
			"ThreadID",
			"URLButton",
			"URLMetadata",
			"UTMInfo",
			"UnauthenticatedBusinessMetadata",
			"UrlTrackingMap",
			"UrlTrackingMapElement",
			"VideoEndCard",
			"VideoMessage",
			"WaffleNonceFetchResponse",
		},
		Enums: []string{
			"AdType",
			"AssociationType",
			"AttachmentType",
			"Attribution",
			"AudienceType",
			"CalendarType",
			"CallOutcome",
			"CallType",
			"CallType",
			"CarouselCardType",
			"CloudAPIThreadControl",
			"ConditionalRevealMessageType",
			"ContentType",
			"CrossAppSource",
			"DataSharingFlags",
			"DayOfWeekType",
			"EditType",
			"EntryPoint",
			"EventResponseType",
			"FontType",
			"Format",
			"ForwardOrigin",
			"FullHistorySyncOnDemandResponseCode",
			"GalaxyFlowActionType",
			"GroupType",
			"HeaderType",
			"HistorySyncChunkRetryResponseCode",
			"HistorySyncType",
			"ImageSourceType",
			"Initiator",
			"InsightDeliveryState",
			"InviteLinkGroupType",
			"InviteType",
			"KeepType",
			"ListType",
			"ListType",
			"LocalChatState",
			"MediaKeyDomain",
			"MediaType",
			"MediaType",
			"MediaType",
			"MessageAddonExpiryType",
			"MusicMessageStyle",
			"OrderStatus",
			"OrderSurface",
			"PairedMediaType",
			"PaymentLinkHeaderType",
			"PeerDataOperationRequestType",
			"PillType",
			"PlaceholderType",
			"PollContentType",
			"PollType",
			"PreviewType",
			"QuotedType",
			"ReminderFrequency",
			"ReminderStatus",
			"SecretEncType",
			"ServiceType",
			"SocialMediaPostType",
			"SplitPaymentStatus",
			"StatusAttributionType",
			"StatusLinkType",
			"StatusNotificationType",
			"StatusQuotedMessageType",
			"StatusSourceType",
			"StatusStickerType",
			"StickerPackOrigin",
			"Style",
			"Surface",
			"ThreadType",
			"Trigger",
			"Type",
			"Type",
			"Type",
			"Type",
			"Type",
			"VideoQuality",
			"VideoSourceType",
			"WebLinkRenderConfig",
			"WebviewPresentationType",
			"WelcomeTrigger",
		},
		Imports: []string{
			"waAICommon/WAWebProtobufsAICommon.proto",
			"waAICommonDeprecated/WAAICommonDeprecated.proto",
			"waAdv/WAAdv.proto",
			"waAea/WAWebProtobufsAea.proto",
			"waCommon/WACommon.proto",
			"waCompanionReg/WACompanionReg.proto",
			"waMmsRetry/WAMmsRetry.proto",
			"waServerSync/WAWebProtobufsServerSync.proto",
			"waStatusAttributions/WAStatusAttributions.proto",
		},
	},
	"waE2EGuest": {
		Dir: "waE2EGuest",
		File: "WAWebProtobufsE2EGuest.proto",
		Package: "WAWebProtobufsE2EGuest",
		GoPackage: "go.mau.fi/whatsmeow/proto/waE2EGuest",
		Messages: []string{
			"ContextInfo",
			"ExtendedTextMessage",
			"Message",
			"MessageContextInfo",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waEphemeral": {
		Dir: "waEphemeral",
		File: "WAWebProtobufsEphemeral.proto",
		Package: "WAWebProtobufsEphemeral",
		GoPackage: "go.mau.fi/whatsmeow/proto/waEphemeral",
		Messages: []string{
			"EphemeralSetting",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waFingerprint": {
		Dir: "waFingerprint",
		File: "WAFingerprint.proto",
		Package: "WAFingerprint",
		GoPackage: "go.mau.fi/whatsmeow/proto/waFingerprint",
		Messages: []string{
			"CombinedFingerprint",
			"FingerprintData",
		},
		Enums: []string{
			"HostedState",
		},
		Imports: []string{
		},
	},
	"waGroupHistory": {
		Dir: "waGroupHistory",
		File: "WAWebProtobufsGroupHistory.proto",
		Package: "WAWebProtobufsGroupHistory",
		GoPackage: "go.mau.fi/whatsmeow/proto/waGroupHistory",
		Messages: []string{
			"GroupHistory",
			"GroupHistoryWithMessageBytes",
			"UnCountedAssociatedMessageList",
			"UnCountedAssociatedMessageListWithMessageBytes",
			"WebMessageInfoWithMessageBytes",
		},
		Enums: []string{
		},
		Imports: []string{
			"waCommon/WACommon.proto",
			"waE2E/WAWebProtobufsE2E.proto",
			"waWeb/WAWebProtobufsWeb.proto",
		},
	},
	"waHistorySync": {
		Dir: "waHistorySync",
		File: "WAWebProtobufsHistorySync.proto",
		Package: "WAWebProtobufsHistorySync",
		GoPackage: "go.mau.fi/whatsmeow/proto/waHistorySync",
		Messages: []string{
			"Account",
			"AutoDownloadSettings",
			"AvatarUserSettings",
			"Conversation",
			"GlobalSettings",
			"GroupParticipant",
			"HistorySync",
			"HistorySyncMsg",
			"IdentityVerificationState",
			"InlineContact",
			"NotificationSettings",
			"PastParticipant",
			"PastParticipants",
			"PhoneNumberToLIDMapping",
			"Pushname",
			"StickerMetadata",
			"WallpaperSettings",
		},
		Enums: []string{
			"BotAIWaitListState",
			"EndOfHistoryTransferType",
			"GroupAppealStatus",
			"HistorySyncType",
			"LeaveReason",
			"MediaVisibility",
			"PrivacySystemMessage",
			"Rank",
		},
		Imports: []string{
			"waChatLockSettings/WAWebProtobufsChatLockSettings.proto",
			"waCommon/WACommon.proto",
			"waE2E/WAWebProtobufsE2E.proto",
			"waSyncAction/WAWebProtobufSyncAction.proto",
			"waWeb/WAWebProtobufsWeb.proto",
		},
	},
	"waLidMigrationSyncPayload": {
		Dir: "waLidMigrationSyncPayload",
		File: "WAWebProtobufLidMigrationSyncPayload.proto",
		Package: "WAWebProtobufLidMigrationSyncPayload",
		GoPackage: "go.mau.fi/whatsmeow/proto/waLidMigrationSyncPayload",
		Messages: []string{
			"LIDMigrationMapping",
			"LIDMigrationMappingSyncPayload",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waMediaEntryData": {
		Dir: "waMediaEntryData",
		File: "WAMediaEntryData.proto",
		Package: "WAMediaEntryData",
		GoPackage: "go.mau.fi/whatsmeow/proto/waMediaEntryData",
		Messages: []string{
			"DownloadableThumbnail",
			"MediaEntry",
			"ProgressiveJpegDetails",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waMediaTransport": {
		Dir: "waMediaTransport",
		File: "WAMediaTransport.proto",
		Package: "WAMediaTransport",
		GoPackage: "go.mau.fi/whatsmeow/proto/waMediaTransport",
		Messages: []string{
			"Ancillary",
			"Ancillary",
			"Ancillary",
			"Ancillary",
			"Ancillary",
			"Ancillary",
			"Ancillary",
			"AudioTransport",
			"AvatarAudio",
			"ContactTransport",
			"DocumentTransport",
			"DownloadableAvatarAnimations",
			"DownloadableThumbnail",
			"ImageTransport",
			"Integral",
			"Integral",
			"Integral",
			"Integral",
			"Integral",
			"Integral",
			"Integral",
			"StickerTransport",
			"Thumbnail",
			"VideoTransport",
			"WAMediaTransport",
		},
		Enums: []string{
			"AnimationsType",
			"Attribution",
			"AudioFormat",
			"HdType",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waMmsRetry": {
		Dir: "waMmsRetry",
		File: "WAMmsRetry.proto",
		Package: "WAMmsRetry",
		GoPackage: "go.mau.fi/whatsmeow/proto/waMmsRetry",
		Messages: []string{
			"MediaRetryNotification",
			"ServerErrorReceipt",
		},
		Enums: []string{
			"ResultType",
		},
		Imports: []string{
		},
	},
	"waMsgApplication": {
		Dir: "waMsgApplication",
		File: "WAMsgApplication.proto",
		Package: "WAMsgApplication",
		GoPackage: "go.mau.fi/whatsmeow/proto/waMsgApplication",
		Messages: []string{
			"ApplicationData",
			"Content",
			"EphemeralSetting",
			"EphemeralSettingMap",
			"MessageApplication",
			"Metadata",
			"Payload",
			"QuotedMessage",
			"Signal",
			"SubProtocolPayload",
		},
		Enums: []string{
			"EphemeralityType",
			"ThreadType",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waMsgTransport": {
		Dir: "waMsgTransport",
		File: "WAMsgTransport.proto",
		Package: "WAMsgTransport",
		GoPackage: "go.mau.fi/whatsmeow/proto/waMsgTransport",
		Messages: []string{
			"Ancillary",
			"BackupDirective",
			"DeviceListMetadata",
			"DeviceSentMessage",
			"ICDCIdentityListDescription",
			"ICDCParticipantDevices",
			"Integral",
			"MessageTransport",
			"Payload",
			"Protocol",
			"SenderKeyDistributionMessage",
		},
		Enums: []string{
			"ActionType",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
		},
	},
	"waMultiDevice": {
		Dir: "waMultiDevice",
		File: "WAMultiDevice.proto",
		Package: "WAMultiDevice",
		GoPackage: "go.mau.fi/whatsmeow/proto/waMultiDevice",
		Messages: []string{
			"AppStateSyncKey",
			"AppStateSyncKeyData",
			"AppStateSyncKeyFingerprint",
			"AppStateSyncKeyId",
			"AppStateSyncKeyRequestMessage",
			"AppStateSyncKeyShareMessage",
			"ApplicationData",
			"Metadata",
			"MultiDevice",
			"Payload",
			"Signal",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waQuickPromotionSurfaces": {
		Dir: "waQuickPromotionSurfaces",
		File: "WAWebProtobufsQuickPromotionSurfaces.proto",
		Package: "WAWebProtobufsQuickPromotionSurfaces",
		GoPackage: "go.mau.fi/whatsmeow/proto/waQuickPromotionSurfaces",
		Messages: []string{
			"Filter",
			"FilterClause",
			"FilterParameters",
			"QP",
		},
		Enums: []string{
			"ClauseType",
			"FilterClientNotSupportedConfig",
			"FilterResult",
		},
		Imports: []string{
		},
	},
	"waReporting": {
		Dir: "waReporting",
		File: "WAWebProtobufsReporting.proto",
		Package: "WAWebProtobufsReporting",
		GoPackage: "go.mau.fi/whatsmeow/proto/waReporting",
		Messages: []string{
			"Config",
			"Field",
			"Reportable",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waRoutingInfo": {
		Dir: "waRoutingInfo",
		File: "WAWebProtobufsRoutingInfo.proto",
		Package: "WAWebProtobufsRoutingInfo",
		GoPackage: "go.mau.fi/whatsmeow/proto/waRoutingInfo",
		Messages: []string{
			"RoutingInfo",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waServerSync": {
		Dir: "waServerSync",
		File: "WAWebProtobufsServerSync.proto",
		Package: "WAWebProtobufsServerSync",
		GoPackage: "go.mau.fi/whatsmeow/proto/waServerSync",
		Messages: []string{
			"CoexStateSync",
			"CollectionMutations",
			"ExitCode",
			"ExternalBlobReference",
			"KeyId",
			"Mutation",
			"SyncdIndex",
			"SyncdMutation",
			"SyncdMutations",
			"SyncdPatch",
			"SyncdRecord",
			"SyncdSnapshot",
			"SyncdValue",
			"SyncdVersion",
		},
		Enums: []string{
			"SyncdOperation",
		},
		Imports: []string{
		},
	},
	"waStatusAttributions": {
		Dir: "waStatusAttributions",
		File: "WAStatusAttributions.proto",
		Package: "WAStatusAttributions",
		GoPackage: "go.mau.fi/whatsmeow/proto/waStatusAttributions",
		Messages: []string{
			"AiCreatedAttribution",
			"ExternalShare",
			"GroupStatus",
			"Metadata",
			"Music",
			"RLAttribution",
			"StatusAttribution",
			"StatusReshare",
		},
		Enums: []string{
			"Source",
			"Source",
			"Source",
			"Source",
			"Type",
		},
		Imports: []string{
		},
	},
	"waSyncAction": {
		Dir: "waSyncAction",
		File: "WAWebProtobufSyncAction.proto",
		Package: "WAWebProtobufSyncAction",
		GoPackage: "go.mau.fi/whatsmeow/proto/waSyncAction",
		Messages: []string{
			"AgentAction",
			"AiThreadRenameAction",
			"AndroidUnsupportedActions",
			"ArchiveChatAction",
			"AutoOrganizeBusinessChatSetting",
			"AvatarUpdatedAction",
			"BizAISettingsNudgeAction",
			"BotWelcomeRequestAction",
			"BroadcastListParticipant",
			"BubbleLockMessageAction",
			"BusinessBroadcastAssociationAction",
			"BusinessBroadcastCampaignAction",
			"BusinessBroadcastInsightsAction",
			"BusinessBroadcastListAction",
			"CallLogAction",
			"CallLogRecord",
			"ChatAssignmentAction",
			"ChatAssignmentOpenedStatusAction",
			"ClearChatAction",
			"CoexV2VersionAction",
			"ContactAction",
			"CtwaPerCustomerDataSharingAction",
			"CustomList",
			"CustomPaymentMethod",
			"CustomPaymentMethodMetadata",
			"CustomPaymentMethodsAction",
			"CustomerDataAction",
			"DeleteChatAction",
			"DeleteIndividualCallLogAction",
			"DeleteMessageForMeAction",
			"DetectedOutcomesStatusAction",
			"ExternalWebBetaAction",
			"Favorite",
			"FavoritesAction",
			"InteractiveMessageAction",
			"KeyExpiration",
			"LabelAssociationAction",
			"LabelEditAction",
			"LabelReorderingAction",
			"LabelSublistAction",
			"LidContactAction",
			"LocaleSetting",
			"LockChatAction",
			"MaibaAIFeaturesControlAction",
			"MarkChatAsReadAction",
			"MarketingMessageAction",
			"MarketingMessageBroadcastAction",
			"MerchantPaymentPartnerAction",
			"MusicUserIdAction",
			"MuteAction",
			"NctSaltSyncAction",
			"NewsletterSavedInterestsAction",
			"NoteEditAction",
			"NotificationActivitySettingAction",
			"NuxAction",
			"OutContactAction",
			"PaidFeature",
			"ParticipantInfo",
			"PatchDebugData",
			"PaymentInfoAction",
			"PaymentTosAction",
			"PinAction",
			"PnForLidChatAction",
			"PrimaryFeature",
			"PrimaryVersionAction",
			"PrivacySettingChannelsPersonalisedRecommendationAction",
			"PrivacySettingDisableLinkPreviewsAction",
			"PrivacySettingRelayAllCalls",
			"PrivateProcessingSettingAction",
			"PushNameSetting",
			"QuickReplyAction",
			"RecentEmojiWeight",
			"RecentEmojiWeightsAction",
			"RemoveRecentStickerAction",
			"RootSecretEntry",
			"SettingsSyncAction",
			"StarAction",
			"StatusPostOptInNotificationPreferencesAction",
			"StatusPrivacyAction",
			"StickerAction",
			"SubscriptionAction",
			"SubscriptionInfo",
			"SubscriptionsSyncV2Action",
			"SyncActionData",
			"SyncActionMessage",
			"SyncActionMessageRange",
			"SyncActionValue",
			"ThreadPinAction",
			"TimeFormatAction",
			"UGCBot",
			"UnarchiveChatsSetting",
			"UserStatusMuteAction",
			"UsernameChatStartModeAction",
			"WASARootSecretAction",
			"WaffleAccountLinkStateAction",
			"WamoUserIdentifierAction",
		},
		Enums: []string{
			"AccountLinkState",
			"AvatarEventType",
			"BizAISettingsCategory",
			"BusinessBroadcastCampaignStatus",
			"CallResult",
			"CallType",
			"ChatStartMode",
			"CollectionName",
			"CollectionName",
			"CollectionNameStr",
			"DisplayMode",
			"InteractiveMessageActionMode",
			"ListType",
			"MaibaAIFeatureStatus",
			"MaibaAIReplyMode",
			"MarketingMessagePrototypeType",
			"MediaQualitySetting",
			"MutationName",
			"MutationProps",
			"NoteType",
			"NotificationActivitySetting",
			"PaymentNotice",
			"Platform",
			"PrivateProcessingStatus",
			"SettingKey",
			"SettingPlatform",
			"SilenceReason",
			"Status",
			"Status",
			"StatusDistributionMode",
		},
		Imports: []string{
			"waChatLockSettings/WAWebProtobufsChatLockSettings.proto",
			"waCommon/WACommon.proto",
			"waDeviceCapabilities/WAWebProtobufsDeviceCapabilities.proto",
		},
	},
	"waSyncdSnapshotRecovery": {
		Dir: "waSyncdSnapshotRecovery",
		File: "WAWebProtobufsSyncdSnapshotRecovery.proto",
		Package: "WAWebProtobufsSyncdSnapshotRecovery",
		GoPackage: "go.mau.fi/whatsmeow/proto/waSyncdSnapshotRecovery",
		Messages: []string{
			"SyncdPlainTextRecord",
			"SyncdSnapshotRecovery",
			"SyncdVersion",
		},
		Enums: []string{
		},
		Imports: []string{
			"waSyncAction/WAWebProtobufSyncAction.proto",
		},
	},
	"waUserPassword": {
		Dir: "waUserPassword",
		File: "WAWebProtobufsUserPassword.proto",
		Package: "WAWebProtobufsUserPassword",
		GoPackage: "go.mau.fi/whatsmeow/proto/waUserPassword",
		Messages: []string{
			"TransformerArg",
			"UserPassword",
			"Value",
		},
		Enums: []string{
			"Encoding",
			"Transformer",
		},
		Imports: []string{
		},
	},
	"waVnameCert": {
		Dir: "waVnameCert",
		File: "WAWebProtobufsVnameCert.proto",
		Package: "WAWebProtobufsVnameCert",
		GoPackage: "go.mau.fi/whatsmeow/proto/waVnameCert",
		Messages: []string{
			"BizAccountLinkInfo",
			"BizAccountPayload",
			"BizIdentityInfo",
			"Details",
			"LocalizedName",
			"VerifiedNameCertificate",
		},
		Enums: []string{
			"AccountType",
			"ActualActorsType",
			"HostStorageType",
			"HostStorageType",
			"VerifiedLevelValue",
		},
		Imports: []string{
		},
	},
	"waWa6": {
		Dir: "waWa6",
		File: "WAWebProtobufsWa6.proto",
		Package: "WAWebProtobufsWa6",
		GoPackage: "go.mau.fi/whatsmeow/proto/waWa6",
		Messages: []string{
			"AppVersion",
			"ClientFinish",
			"ClientHello",
			"ClientPayload",
			"DNSSource",
			"DevicePairingRegistrationData",
			"HandshakeMessage",
			"InteropData",
			"ServerHello",
			"UserAgent",
			"WebInfo",
			"WebdPayload",
		},
		Enums: []string{
			"AccountType",
			"ConnectReason",
			"ConnectType",
			"DNSResolutionMethod",
			"DeviceType",
			"DistributionChannel",
			"HandshakePqMode",
			"IOSAppExtension",
			"Platform",
			"Product",
			"ReleaseChannel",
			"TrafficAnonymization",
			"WebSubPlatform",
		},
		Imports: []string{
		},
	},
	"waWeb": {
		Dir: "waWeb",
		File: "WAWebProtobufsWeb.proto",
		Package: "WAWebProtobufsWeb",
		GoPackage: "go.mau.fi/whatsmeow/proto/waWeb",
		Messages: []string{
			"Citation",
			"CommentMetadata",
			"EventAdditionalMetadata",
			"EventResponse",
			"GroupHistoryBundleInfo",
			"GroupHistoryIndividualMessageInfo",
			"InteractiveMessageAdditionalMetadata",
			"KeepInChat",
			"LegacyMessage",
			"MediaData",
			"MessageAddOn",
			"MessageAddOnContextInfo",
			"NotificationMessageInfo",
			"PaymentInfo",
			"PhotoChange",
			"PinInChat",
			"PollAdditionalMetadata",
			"PollNameHashHistoryEntry",
			"PollUpdate",
			"PremiumMessageInfo",
			"QuarantinedMessage",
			"Reaction",
			"ReportingTokenInfo",
			"ScheduledMessageMetadata",
			"StatusMentionMessage",
			"StatusPSA",
			"UserReceipt",
			"WebFeatures",
			"WebMessageInfo",
			"WebNotificationsInfo",
		},
		Enums: []string{
			"BizPrivacyStatus",
			"Currency",
			"Flag",
			"MessageAddOnType",
			"ProcessState",
			"Status",
			"Status",
			"StubType",
			"TxnStatus",
			"Type",
		},
		Imports: []string{
			"waCommon/WACommon.proto",
			"waE2E/WAWebProtobufsE2E.proto",
		},
	},
	"waWebLabyrinthWaWasm": {
		Dir: "waWebLabyrinthWaWasm",
		File: "WAWebLabyrinthWaWasm.proto",
		Package: "WAWebLabyrinthWaWasm",
		GoPackage: "go.mau.fi/whatsmeow/proto/waWebLabyrinthWaWasm",
		Messages: []string{
			"CreateBackupInput",
			"CreateBackupOutput",
			"DecryptMessageInput",
			"DecryptMessageOutput",
			"DeriveMessageKeyInput",
			"DeriveMessageKeyOutput",
			"DeviceOutput",
			"EncryptMessageInput",
			"EncryptMessageOutput",
			"EncryptedSecretValuesOutput",
			"Epoch0Output",
			"LabyrinthWaCommand",
			"OrfThreadIdInput",
			"OrfThreadIdOutput",
			"RotateEpochInput",
			"RotateEpochMemberEdge",
			"RotateEpochMemberInput",
			"RotateEpochOutput",
			"VirtualDeviceOutput",
		},
		Enums: []string{
		},
		Imports: []string{
		},
	},
	"waWinUIApi": {
		Dir: "waWinUIApi",
		File: "WAWinUIApi.proto",
		Package: "WAWinUIApi",
		GoPackage: "go.mau.fi/whatsmeow/proto/waWinUIApi",
		Messages: []string{
			"MsgKey",
			"PositronChat",
			"PositronContact",
			"PositronData",
			"PositronGroupMetadata",
			"PositronGroupParticipants",
			"PositronMessage",
			"PositronReaction",
			"WID",
		},
		Enums: []string{
			"PositronDataSource",
		},
		Imports: []string{
		},
	},
}

// TypeToPackage maps known top-level type names to their package directory.
var TypeToPackage = make(map[string]string)

func init() {
	for dir, pkg := range Packages {
		for _, m := range pkg.Messages {
			TypeToPackage[m] = dir
		}
		for _, e := range pkg.Enums {
			TypeToPackage[e] = dir
		}
	}
}

// IsScalarType returns true if the type is a primitive protobuf scalar.
func IsScalarType(t string) bool {
	switch strings.ToLower(t) {
	case "double", "float", "int32", "int64", "uint32", "uint64",
		"sint32", "sint64", "fixed32", "fixed64", "sfixed32", "sfixed64",
		"bool", "string", "bytes":
		return true
	default:
		return false
	}
}

// LookupPackageForType finds the package directory for a given type name.
// If the type is unknown, it attempts heuristic inference based on common prefixes.
func LookupPackageForType(typeName string) string {
	clean := strings.TrimPrefix(typeName, ".")
	if IsScalarType(clean) {
		return ""
	}
	if pkg, ok := TypeToPackage[clean]; ok {
		return pkg
	}
	if strings.HasPrefix(typeName, "Instamadillo") {
		return "instamadilloAddMessage"
	}
	if strings.HasPrefix(typeName, "ADV") {
		return "waAdv"
	}
	if strings.HasPrefix(typeName, "Bot") || strings.HasPrefix(typeName, "AI") {
		return "waAICommon"
	}
	if strings.HasPrefix(typeName, "HistorySync") {
		return "waHistorySync"
	}
	if strings.HasPrefix(typeName, "SyncAction") {
		return "waSyncAction"
	}
	// Default fallthrough to waE2E for messages/enums
	return "waE2E"
}
